[1] Implementation Of The Graphic Charter
VictorNain26/formation-front pull request #2
Opened 2022-07-09 14:59 UTC by VictorNain26

[Carte trello](https://trello.com/c/geaRPTub/3-1-cas-pratique-mise-en-place-de-la-charte-graphique)

2022-07-11 07:32 UTC, virginie-perrichon requested changes
Quelques retours en plus : 
- pour les icons, il faut des svg, c'est beaucoup plus simple à manier sans perdre en qualité, ne pas oublier d'ajouter des width, height et alt, sur les images (même svg car on les importe en tant que `image_tag`
- Le nom des images doit être en minuscule (choisir le type de trait pour séparer et garder tout le temps le même) 
- Pour la lisibilité du code, dans les vues il faut passer à la ligne le contenu des balises (avec indentation)

2022-07-11 07:32 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_cards.scss
> +  box-shadow: 0px 0px 30px rgba($dark, 0.3);
$card-box-shadow 
Il faut activer la variable dans le fichier `variables/variables` 

`$enable-shadows: true`

2022-07-11 07:32 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_cards.scss
> +  }
En faisant ainsi, toutes tes cards auront ses propriétés, ce qui n'est pas forcément l'effet voulu 
Il faut que tu utilises au max les classes Bootstrap dans ta vue. 

Si tu as besoin de custom spécifiquement pour les cartes projet et que tu ne peux pas utiliser de classes Bootstrap, tu peux créer une class `project-card` et là tu customise pour ne l'appliquer que sur ces cartes

2022-07-11 07:32 UTC, virginie-perrichon commented on app/assets/stylesheets/rules.scss
> +}
Euh what ? Si tu as besoin de faire du flex, utilise le directement dans le code

2022-07-11 07:32 UTC, virginie-perrichon commented on app/assets/stylesheets/variables/_fonts.scss
> +$secondary-family: "Co", sans-serif;
On ne peut pas avoir la font en local ? (demande à Nico) pour les font google généralement je dis ok, mais je préfère au max qu'on évite les cdn pour des raisons de perf

2022-07-11 07:32 UTC, virginie-perrichon commented on app/assets/stylesheets/variables/_shadow.scss
> +$btn-shadow-active: 0px 0px 30px rgba($dark, 0.2);
Ces variables sont rattachées aux btn, il faut qu'elles aille dans ce fichier

2022-07-11 07:32 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_cards.scss
> +    background-color: #EBEBEB;
Utiliser que des variables

2022-07-12 16:40 UTC, virginie-perrichon requested changes

2022-07-12 16:40 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_buttons.scss
> +}
variable `$btn-box-shadow: `

2022-07-12 16:40 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_cards.scss
> +    }
Les svg ce n'est que pour les icons, png pour les images avec transparence, et les autres c'est jpeg (style image project)

2022-07-12 16:40 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_cards.scss
> +    background-color: #EBEBEB;
variable couleur, jamais les couleurs en dur

2022-07-12 16:40 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_paginations.scss
> +}
Faudrait pas le rassembler avec ce qu'il y a en haut ? 

.page-item 
```suggestion
.page-item {
  .page-link {
    font-size: 1.25rem;
    
    span { ... }
  }
}
```

2022-07-12 16:40 UTC, virginie-perrichon commented on app/javascript/application.js
> +import "custom/main"
J'avais pas vu le nom de fichier oulala 
`input_files_custom` si tu veux mais l'idée c'est aussi de scindé les fichiers JS pas de toute mettre dans un

2022-07-12 16:40 UTC, virginie-perrichon commented on app/views/homes/index.html.erb
> +           name="profile[identity_proofs_attributes][0][file_front]">
```suggestion
    <input 
      required="required"
      id="project_owner_identity_proofs_file_front"
      class="form-control-file custom-file-input"
      type="file"
      name="profile[identity_proofs_attributes][0][file_front]"
     >
```

2022-07-12 16:40 UTC, virginie-perrichon commented on app/views/homes/index.html.erb
> +    </div>
indentation

2022-07-12 16:40 UTC, virginie-perrichon commented on app/views/homes/index.html.erb
> +  <div class="badge rounded-pill bg-success ms-2">Accepté</div>
On met pas de texte directement dans une div, il faut passer par des `<p>` `<span>`, balise titre etc

2022-07-12 16:40 UTC, virginie-perrichon commented on app/views/homes/index.html.erb
> +    <span class="ms-3 my-auto file-content font-weight-normal text-truncate col-8 pe-4">Choisir un fichier</span>
```suggestion
    <span class="ms-3 my-auto file-content font-weight-normal text-truncate col-8 pe-4">
      Choisir un fichier
    </span>
```

2022-07-12 16:40 UTC, virginie-perrichon commented on app/views/homes/index.html.erb
> +  <span class="card-img-top shadow-lg"><%= show_svg("card-img-top") %></span>
Pas d'image dans des `span`, faut mettre dans des div si besoin

2022-07-12 16:40 UTC, virginie-perrichon commented on app/views/homes/index.html.erb
> +    </p>
```suggestion
    <p class="card-text mb-4 fs-6 fw-light text-dark">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Dictum ullamcorper vel dolor tellus varius.
       Venenatis blandit diam mauris mauris urna duis.
    </p>
```

2022-07-18 08:52 UTC, virginie-perrichon requested changes

2022-07-18 08:52 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_buttons.scss
> +  }
Mettre à la racine du btn-

2022-07-18 08:52 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_buttons.scss
> +  }
ici aussi

2022-07-18 08:52 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_progress.scss
> +    align-self: center;
à supprimer ! et à remplacer par `text-align: center`

2022-07-18 08:52 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_progress.scss
> +  .progress {
saut de ligne

2022-07-18 08:52 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_progress.scss
> +    .progress-bar {
saut de ligne

2022-07-18 08:52 UTC, virginie-perrichon commented on app/assets/stylesheets/variables/_fonts.scss
> +  src: url(b9f645c1cc5cb8e2dc45b791ab656622.ttf) format("truetype");
changer le nom du fichier :)

2022-07-20 08:57 UTC, virginie-perrichon requested changes

2022-07-20 08:57 UTC, virginie-perrichon commented on app/javascript/inlineSvg.js
> +});
tu ne peux pas utiliser un package plutôt avec yarn ?

2022-07-20 08:57 UTC, virginie-perrichon commented on app/views/layouts/application.html.erb
> +    <%= javascript_include_tag 'inlineSvg.js', type: 'module' %>
il faudrait ensuite appeler ton fichier qui contient `init inlineSVG` dans `application.js` comme les autres fichier js

2022-07-20 09:33 UTC, VictorNain26 commented on app/javascript/inlineSvg.js
> +});
J'ai voulu tester les import map qui a été intégré dans rails 7 (https://github.com/rails/importmap-rails) du coup pas de yarn ! Je doute de la viabilité en prod/gros projets mais du coup pour mon cas je me suis dis que c’était le moment de tester.

2022-07-25 08:25 UTC, merged