[2] Navbar
VictorNain26/formation-front pull request #3
Opened 2022-07-12 07:23 UTC by VictorNain26

[Trello](https://trello.com/c/LDXmQXoI/5-2-navbar)

2022-07-13 07:22 UTC, virginie-perrichon requested changes

2022-07-13 07:22 UTC, virginie-perrichon commented on app/views/partials/_navbar.html.erb
> +    <div class="container-fluid">
Peut de change que tu utilise un container-fluid sur une de nos plateforme au niveau de la navbar, ça veut dire que sur un grand écran, les éléments se trouvent aux opposés de la page

2022-07-13 07:22 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_navbar.scss
> +}
à revoir si vraiment besoin

2022-07-13 07:22 UTC, virginie-perrichon commented on app/views/partials/_navbar.html.erb
> +          <%= image_tag "logo.png" %>
Il faut fixer dans le html width height et alt

2022-07-13 07:22 UTC, virginie-perrichon commented on app/views/partials/_navbar.html.erb
> +        <%= render 'partials/navbar/mobile_navs'%>
Manque un espace avec la balise fermante

2022-07-13 07:22 UTC, virginie-perrichon commented on app/views/partials/navbar/_mobile_navs.html.erb
> +      <button type="button" class="btn btn-primary"><%= link_to "Se connecter", new_user_session_path %></button>
Pourquoi avoir utiliser une balise `button` ici ? tu peux mettre directement le design `btn` en classe du `link_to`

2022-07-15 15:52 UTC, virginie-perrichon requested changes

2022-07-15 15:52 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_navbar.scss
> +  min-height: 7.438rem;
a quoi sert le min-height ?

2022-07-15 15:52 UTC, virginie-perrichon commented on app/views/partials/_navbar.html.erb
> +      <div class="collapse navbar-collapse justify-content-end col me-5" id="navbarToggler">
n'oublie pas d'ajouter un container pour éviter que les éléments se retrouvent aux opposés de l'écran

2022-07-15 15:52 UTC, virginie-perrichon commented on app/views/partials/navbar/_mobile_navs.html.erb
> +    </li>
n'oublie pas de remettre les href juste après l'ouverture de la balise `a`

2022-07-15 15:52 UTC, virginie-perrichon commented on app/views/partials/navbar/_navs.html.erb
> +<ul class="navbar-nav col d-none d-lg-flex justify-content-end align-items-center me-5">
pas dans un col, mais bien dans un container !

2022-07-20 08:19 UTC, virginie-perrichon requested changes

2022-07-20 08:19 UTC, virginie-perrichon commented on app/assets/stylesheets/components/_navbar.scss
> +  height: 7.438rem;
En fait non je voulais dire pourquoi fixer une taille ? pas besoin et tu risque d'avoir des pb de débordement s'il y a des modifs !

2022-07-20 09:53 UTC, VictorNain26 commented on app/assets/stylesheets/components/_navbar.scss
> +  height: 7.438rem;
Il vaut mieux que je mette du padding ?

2022-07-20 13:57 UTC, virginie-perrichon commented
Pour moi cette PR est good ! 
Quand la charte graphique sera mergée, tu pourras merge celle-ci !

2022-07-25 08:26 UTC, merged