[3] Sidebar
VictorNain26/formation-front pull request #4
Opened 2022-07-12 09:48 UTC by VictorNain26

[Trello](https://trello.com/c/CzOoFRZb/4-3-int%C3%A9gration-du-dashboard-side-menu)

2022-07-15 15:55 UTC, virginie-perrichon requested changes

2022-07-15 15:55 UTC, virginie-perrichon commented on app/views/partials/_sidebar.html.erb
> +<ul class="sidebar nav nav-pills flex-column col-2 shadow d-none d-lg-flex">
Il me semble que la side menu doit être en position sticky ?

2022-07-20 10:12 UTC, VictorNain26 commented on app/assets/stylesheets/components/_navbar.scss
> +  min-width: 291.88px;
J'ai du reprendre la valeur que j'ai trouvé dans l'inspecteur mais de toute façon normalement je les convertis en `rem` je sais pas pourquoi je l'ai pas fait ici ahah

2022-07-20 15:01 UTC, virginie-perrichon requested changes
Si tu peux ajouter les I18n aussi !

2022-07-20 15:01 UTC, virginie-perrichon commented on app/views/partials/navbar/_mobile_sidebar.html.erb
> +    <% end %>
Indentation 

```suggestion
    <%= link_to destroy_user_session_path,
        method: :delete,
        class: "nav-link link-dark fw-light my-3 px-5" 
     do %>
      <%= svg_tag("icon-logout", class: "col-2 me-3") %>
      <span>Déconnexion</span>
    <% end %>
```

2022-07-20 15:07 UTC, VictorNain26 commented on app/views/partials/navbar/_mobile_sidebar.html.erb
> +    <% end %>
J'ai une erreur chez moi si je passe le do sur une autre ligne, je sais pas si c'est le cas chez toi aussi ?

2022-07-25 08:27 UTC, merged